language: php

php:
  - 7.1
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

notifications:
  email:
    recipients:
      - team@boltics.com
    on_success: never # default: change
    on_failure: always

before_script:
  - composer install --prefer-dist --optimize-autoloader --quiet --no-interaction
  - mkdir -p build/logs
  - wget -c -nc --retry-connrefused --tries=0 https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - chmod +x coveralls.phar
  - php coveralls.phar --version

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:

after_success:
  - travis_retry php coveralls.phar

sudo: false
